export interface Restaurant {
  id: number;
  name: string;
  nameEn: string;
  cuisine: string;
  bgImage: string;
  logo: string;
  description: string;
  hours: string;
  priceRange: string;
  location: string;
}

export const RESTAURANTS: Restaurant[] = [
  {
    id: 1,
    name: "برنش آند كيك",
    nameEn: "Brunch and Cake",
    cuisine: "عالمي",
    bgImage: "/images/restaurants/brunch-bg.jpg",
    logo: "/images/restaurants/brunch-logo.jpg",
    description: "مطعم عالمي يقدم أشهى أطباق البرنش والكيك في أجواء مميزة بقلب الدرعية التاريخية.",
    hours: "8:00 ص - 11:00 م",
    priceRange: "٨٠ - ٢٠٠ ريال",
    location: "مطل البجيري، الدرعية",
  },
  {
    id: 3,
    name: "كوفا للحلويات",
    nameEn: "Cova Pasticceria",
    cuisine: "حلويات إيطالية",
    bgImage: "/images/restaurants/cova-bg.jpg",
    logo: "/images/restaurants/cova-logo.jpg",
    description: "تجربة إيطالية أصيلة في عالم الحلويات والمعجنات الفاخرة منذ عام 1817.",
    hours: "9:00 ص - 12:00 ص",
    priceRange: "٥٠ - ١٥٠ ريال",
    location: "مطل البجيري، الدرعية",
  },
  {
    id: 5,
    name: "لونق تشيم",
    nameEn: "Long Chim",
    cuisine: "تايلندي",
    bgImage: "/images/restaurants/longchim-bg.jpg",
    logo: "/images/restaurants/longchim-logo.png",
    description: "مطعم تايلندي يقدم أطباقاً تقليدية بنكهات أصيلة من شوارع بانكوك.",
    hours: "12:00 م - 12:00 ص",
    priceRange: "٩٠ - ٢٥٠ ريال",
    location: "مطل البجيري، الدرعية",
  },
  {
    id: 6,
    name: "ميز",
    nameEn: "Maiz",
    cuisine: "سعودي",
    bgImage: "/images/restaurants/maiz-bg.jpg",
    logo: "/images/restaurants/maiz-logo.jpg",
    description: "مطعم سعودي يقدم أطباقاً تراثية بلمسة عصرية تعكس ثقافة المملكة.",
    hours: "11:00 ص - 1:00 ص",
    priceRange: "٧٠ - ٢٠٠ ريال",
    location: "مطل البجيري، الدرعية",
  },
  {
    id: 7,
    name: "سارابيث",
    nameEn: "Sarabeth's",
    cuisine: "أمريكي",
    bgImage: "/images/restaurants/sarabeth-bg.jpg",
    logo: "/images/restaurants/sarabeth-logo.jpg",
    description: "مطعم أمريكي شهير يُقدم أفضل وجبات الإفطار والبرنش مع المربيات المميزة.",
    hours: "8:00 ص - 11:00 م",
    priceRange: "٨٠ - ٢٢٠ ريال",
    location: "مطل البجيري، الدرعية",
  },
  {
    id: 8,
    name: "سموير",
    nameEn: "Somewhere",
    cuisine: "عربي",
    bgImage: "/images/restaurants/somewhere-bg.jpg",
    logo: "/images/restaurants/somewhere-logo.jpg",
    description: "مطعم عربي يقدم تجربة طعام فريدة مستوحاة من المطبخ العربي الأصيل.",
    hours: "4:00 م - 1:00 ص",
    priceRange: "١٠٠ - ٣٠٠ ريال",
    location: "مطل البجيري، الدرعية",
  },
  {
    id: 9,
    name: "فيلا ماماز",
    nameEn: "Villa Mamas",
    cuisine: "بحريني",
    bgImage: "/images/restaurants/villamamas-bg.jpg",
    logo: "/images/restaurants/villamamas-logo.png",
    description: "مطعم بحريني يقدم أطباقاً خليجية تقليدية بلمسة عصرية راقية.",
    hours: "12:00 م - 12:00 ص",
    priceRange: "٩٠ - ٢٥٠ ريال",
    location: "مطل البجيري، الدرعية",
  },
  {
    id: 10,
    name: "انجلينا",
    nameEn: "Angelina",
    cuisine: "فرنسي",
    bgImage: "/images/restaurants/angelina-bg.jpg",
    logo: "/images/restaurants/angelina-logo.jpg",
    description: "مقهى فرنسي فاخر يشتهر بالشوكولاتة الساخنة والمعجنات الباريسية منذ 1903.",
    hours: "9:00 ص - 11:00 م",
    priceRange: "٦٠ - ١٨٠ ريال",
    location: "مطل البجيري، الدرعية",
  },
  {
    id: 11,
    name: "سَـم+ثينغز",
    nameEn: "Sum+Things",
    cuisine: "عالمي",
    bgImage: "/images/restaurants/sumthings-bg.jpg",
    logo: "/images/restaurants/sumthings-logo.jpg",
    description: "مطعم عالمي يقدم مزيجاً مبتكراً من الأطباق المتنوعة والنكهات الفريدة.",
    hours: "11:00 ص - 12:00 ص",
    priceRange: "٨٠ - ٢٠٠ ريال",
    location: "مطل البجيري، الدرعية",
  },
  {
    id: 12,
    name: "فلامينغو روم",
    nameEn: "Flamingo Room",
    cuisine: "أوروبي",
    bgImage: "/images/restaurants/flamingo-bg.jpg",
    logo: "/images/restaurants/flamingo-logo.jpg",
    description: "مطعم أوروبي فاخر يقدم تجربة طعام راقية بأجواء أنيقة.",
    hours: "5:00 م - 1:00 ص",
    priceRange: "١٥٠ - ٤٠٠ ريال",
    location: "مطل البجيري، الدرعية",
  },
  {
    id: 16,
    name: "تكية",
    nameEn: "Takya",
    cuisine: "سعودي",
    bgImage: "/images/restaurants/takya-bg.jpg",
    logo: "/images/restaurants/takya-logo.jpg",
    description: "مطعم سعودي أصيل يقدم أشهى الأطباق التراثية في أجواء تاريخية.",
    hours: "12:00 م - 1:00 ص",
    priceRange: "٦٠ - ١٨٠ ريال",
    location: "مطل البجيري، الدرعية",
  },
  {
    id: 17,
    name: "ألتوبيانو",
    nameEn: "Altopiano",
    cuisine: "إيطالي",
    bgImage: "/images/restaurants/altopiano-bg.jpg",
    logo: "/images/restaurants/altopiano-logo.jpg",
    description: "مطعم إيطالي يقدم أطباق البيتزا والباستا الأصيلة بمكونات طازجة.",
    hours: "12:00 م - 12:00 ص",
    priceRange: "١٠٠ - ٢٨٠ ريال",
    location: "مطل البجيري، الدرعية",
  },
  {
    id: 19,
    name: "أفريكان لاونج",
    nameEn: "African Lounge",
    cuisine: "أفريقي",
    bgImage: "/images/restaurants/african-bg.png",
    logo: "/images/restaurants/african-logo.png",
    description: "تجربة أفريقية فريدة تجمع بين النكهات الأصيلة والأجواء المميزة.",
    hours: "4:00 م - 1:00 ص",
    priceRange: "٩٠ - ٢٥٠ ريال",
    location: "مطل البجيري، الدرعية",
  },
  {
    id: 20,
    name: "ميزون أسولين",
    nameEn: "MAISON ASSOULINE",
    cuisine: "مقهى فاخر",
    bgImage: "/images/restaurants/assouline-bg.jpg",
    logo: "/images/restaurants/assouline-logo.jpg",
    description: "مقهى فاخر يجمع بين عالم الكتب والفن مع تجربة مشروبات وحلويات راقية.",
    hours: "10:00 ص - 11:00 م",
    priceRange: "٥٠ - ١٥٠ ريال",
    location: "مطل البجيري، الدرعية",
  },
  {
    id: 21,
    name: "دولتشي اند غابانا كافيه",
    nameEn: "Dolce and Gabbana Caffe",
    cuisine: "مقهى إيطالي",
    bgImage: "/images/restaurants/dg-bg.jpg",
    logo: "/images/restaurants/dg-logo.jpg",
    description: "مقهى إيطالي فاخر من دولتشي اند غابانا يقدم تجربة فريدة بأجواء أنيقة.",
    hours: "9:00 ص - 12:00 ص",
    priceRange: "٨٠ - ٢٥٠ ريال",
    location: "مطل البجيري، الدرعية",
  },
  {
    id: 22,
    name: "ليزا",
    nameEn: "LIZA",
    cuisine: "لبناني",
    bgImage: "/images/restaurants/liza-bg.jpg",
    logo: "/images/restaurants/liza-logo.png",
    description: "مطعم لبناني يقدم أطباقاً شرقية أصيلة بلمسة عصرية.",
    hours: "12:00 م - 12:00 ص",
    priceRange: "١٠٠ - ٣٠٠ ريال",
    location: "مطل البجيري، الدرعية",
  },
];

export function getRestaurantById(id: number): Restaurant | undefined {
  return RESTAURANTS.find((r) => r.id === id);
}
